Refactor ancestor check in branch deploy script
Make it easier to check what is happening - what is the return code,
and what happens when the return code is 0, 1 and higher.

diff --git a/.github/workflows/branch-deploy.yml b/.github/workflows/branch-deploy.yml
--- a/.github/workflows/branch-deploy.yml
+++ b/.github/workflows/branch-deploy.yml
@@ -15,8 +15,11 @@ jobs:
           with:
             ref: master
         - uses: actions/checkout@v2
-        - run: | # Command returns 0 when master is ancestor, 1 if it is not (other positive numbers on error)
-            if git merge-base --is-ancestor "$(git rev-parse origin/master)" HEAD; then
+        - run: | # git merge-base returns 0 when master is ancestor, 1 if it is not (other positive numbers on error)
+            git merge-base --is-ancestor "$(git rev-parse origin/master)" HEAD
+            return_code=$?
+            echo "Return code of 'git merge-base': ${return_code}"
+            if [[ return_code -gt 0 ]]; then
               echo "You have to merge origin/master before you can deploy a branch."; exit 1
             fi
    build:
